---
services:
  odoo:
    image: odoo:${ODOO_VERSION:-17}
    build:
      context: .
      args:
          ODOO_VERSION: ${ODOO_VERSION:-17}
      dockerfile: ./Dockerfile

    restart: always
    depends_on:
      - postgresql
    ports:
      - "8069:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./extra-addons:/mnt/extra-addons
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
      - HOST=postgresql
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=8069
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    secrets:
      - postgresql_password
    networks:
      - odoo
      - proxy

  postgresql:
    image: postgres:${POSTGRESQL_VERSION}
    restart: always
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgresql-data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password
    networks:
      - odoo

volumes:
  odoo-data:
  postgresql-data:

networks:
  odoo:
  proxy:
    external: true
    name: http-proxy_proxy

secrets:
  postgresql_password:
    file: .odoo_pg_pass
